server {
  listen 80;
  server_name asafaeirad.com;

  root /var/www/asafaeirad.com;

  location / {
    if ($http_user_agent ~* "curl") {
      rewrite ^(.*)$ /index.txt last;
    }

    try_files $uri $uri/ /index.html;
  }
}
